import InvoiceDetailModalType from '../types/InvoiceDetailModalType';
import InvoiceHistoryAccordionStatus from '../types/InvoiceHistoryAccordionStatus';
import InvoiceStatus from '../types/InvoiceStatus';
import LoadingState from '../../../../components/PageView/LoadingState';
import SaveActionType from '../types/SaveActionType';
import formatIsoDate from '../../../../common/valueFormatters/formatDate/formatIsoDate';

export const DEFAULT_UNITS = '1';
export const DEFAULT_DISCOUNT = '0';

const getDefaultState = () => ({
  businessId: '',
  region: '',
  invoiceId: '',
  quoteId: undefined,
  duplicateId: undefined,
  loadingState: LoadingState.LOADING,
  alert: undefined,
  modalType: InvoiceDetailModalType.NONE,
  modalAlert: undefined,
  isModalSubmitting: false,
  isPageEdited: false,
  isSubmitting: false,
  isAbnLoading: false,
  saveActionType: SaveActionType.SAVE,
  invoice: {
    id: '',
    layout: '',
    customerId: '',
    address: '',
    note: '',
    invoiceNumber: '',
    purchaseOrderNumber: '',
    issueDate: formatIsoDate(new Date()),
    isAllowOnlinePayments: false,
    isTaxInclusive: true,
    expirationTerm: '',
    expirationDays: '',
    chargeForLatePayment: 0,
    discountForEarlyPayment: 0,
    numberOfDaysForDiscount: 0,
    amountPaid: '0',
    status: InvoiceStatus.NONE,
    taxExclusiveFreightAmount: '0',
    freightTaxAmount: '0',
    freightTaxCodeId: '0',
    lines: [],
  },
  newLine: {
    units: '',
    itemId: '',
    description: '',
    unitPrice: '',
    unitOfMeasure: '',
    jobId: '',
    taxCodeId: '',
    accountId: '',
    discount: '',
    amount: '',
  },
  originalAmountDue: '0',
  template: {
    defaultTemplate: '',
    templateOptions: [],
  },
  comments: [],
  serialNumber: '',
  accountOptions: [],
  taxCodeOptions: [],
  expirationTermOptions: [],
  emailInvoice: {
    hasEmailReplyDetails: false,
    isEmailMeACopy: false,
    businessName: '',
    ccToEmail: [''],
    fromEmail: '',
    fromName: '',
    messageBody: '',
    subject: '',
    toEmail: [''],
    toName: '',
    attachments: [],
    templateName: '',
    emailDefaultSettings: {},
  },
  exportPdf: {
    template: '',
  },
  subscription: {
    isTrial: false,
    monthlyLimit: {
      hasHitLimit: false,
    },
    isUpgradeModalShowing: false,
  },
  payDirect: {
    isLoading: true,
    isServiceAvailable: false,
    isRegistered: false,
    registrationUrl: '',
  },
  abn: undefined,
  isLineAmountDirty: false,
  invoiceHistory: [],
  invoiceHistoryAccordionStatus: InvoiceHistoryAccordionStatus.LOADING,
  redirectRefJournalId: '',
  redirectRefJournalType: '',
  isPreConversion: false,
  showPreConversionAlert: false,
  customerQuotes: [],
  isLoadingCustomerQuotes: true,
  customerQuoteId: '',
  viewedAccountToolTip: false,
});

export default getDefaultState;
