export default ({ closeTasks }) => ({
  businessDetailsConfirmed: () => closeTasks({ closeEvent: 'businessDetailsConfirmed' }),
  usersInvited: () => closeTasks({ closeEvent: 'usersInvited' }),
  pageLoaded: moduleName => closeTasks({ closeEvent: `${moduleName}Loaded` }),
  setupBusinessDetails: () => closeTasks({ closeEvent: 'setupBusinessDetails' }),
  updatedEmailSettings: () => closeTasks({ closeEvent: 'updatedEmailSettings' }),
  customisedEmailDefaults: () => closeTasks({ closeEvent: 'customisedEmailDefaults' }),
  addedPaymentDetails: () => closeTasks({ closeEvent: 'addedPaymentDetails' }),
  uploadedLogo: () => closeTasks({ closeEvent: 'uploadedLogo' }),
  learnPayrollCompleted: () => closeTasks({ closeEvent: 'learnPayrollCompleted' }),
  learnInTrayCompleted: () => closeTasks({ closeEvent: 'learnInTrayCompleted' }),
  learnBankingCompleted: () => closeTasks({ closeEvent: 'learnBankingCompleted' }),
  inTrayBillSaved: () => closeTasks({ closeEvent: 'inTrayBillSaved' }),
  inTrayUploadOptionsClosed: () => closeTasks({ closeEvent: 'inTrayUploadOptionsClosed' }),
  payrollGeneralSettingsSaved: () => closeTasks({ closeEvent: 'payrollGeneralSettingsSaved' }),
  setupPayrollDetailsCompleted: () => closeTasks({ closeEvent: 'setupPayrollDetailsCompleted' }),
  addPaymentDetailsAndSaveSuccess: () => closeTasks({ closeEvent: 'addPaymentDetailsAndSaveSuccess' }),
});
