import LoadingState from '../../../../components/PageView/LoadingState';
import formatIsoDate from '../../../../common/valueFormatters/formatDate/formatIsoDate';

export const DEFAULT_UNITS = '1';
export const DEFAULT_DISCOUNT = '0';

export const getDefaultState = () => ({
  businessId: '',
  region: '',
  recurringTransactionId: '',
  transactionType: '',
  schedule: {
    name: '',
    frequency: '',
    recurrence: '',
    isAutomaticallyRecorded: false,
    nextDueDate: formatIsoDate(new Date()),
    secondDueDate: '',
    endDate: '',
    numberOfTimes: '',
    remainingTimes: '',
    shouldNotifyUser: false,
    notifyUserId: '',
    shouldUseCustomNumber: false,
    customNumber: '',
  },
  bill: {
    layout: '',
    supplierId: '',
    supplierAddress: '',
    expirationTerm: '',
    expirationDays: '',
    isTaxInclusive: true,
    isReportable: false,
    lines: [],
    taxExclusiveFreightAmount: '0',
    freightTaxAmount: '0',
    freightTaxCodeId: '0',
    note: '',
    memo: '',
    chargeForLatePayment: 0,
    discountForEarlyPayment: 0,
    numberOfDaysForDiscount: 0,
  },
  newLine: {
    id: '',
    type: '',
    description: '',
    amount: '',
    jobId: '',
    taxCodeId: '',
    accountId: '',
    units: '',
    discount: '',
    unitPrice: '',
    itemId: '',
  },
  expirationTermOptions: [],
  accountOptions: [],
  taxCodeOptions: [],
  alert: undefined,
  modalType: undefined,
  loadingState: LoadingState.LOADING,
  isSubmitting: false,
  isAbnLoading: false,
  isPageEdited: false,
  isLineEdited: false,
  abn: undefined,
  isRecurringTransactionEnabled: false,
});
