steps:

  - name: ':traffic_light: Unit Tests'
    command: ./ops/bin/test
    agents:
      queue: cacc-prod-dflt

  - name: ':book: Linting'
    command: ./ops/bin/lint
    agents:
      queue: cacc-prod-dflt

  - wait

  - name: ':package: :hatched_chick: Build Preprod Javascript'
    command: ./ops/bin/build preprod
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build-preprod.tar.gz"

  - name: ':package: :eagle: Build Prod Javascript'
    command: ./ops/bin/build prod
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build.tar.gz"

  - wait

  - name: ':rocket: :hatched_chick: Deploy Preprod App'
    command: ./ops/bin/deploy preprod
    branches: master
    agents:
      queue: cacc-prod-dflt

  - block

  - name: ':rocket: :eagle: Deploy Prod App'
    command: ./ops/bin/deploy prod
    branches: master
    agents:
      queue: cacc-prod-dflt
