steps:

  - name: ':traffic_light: Unit Tests'
    command: ./ops/bin/test
    agents:
      queue: cacc-prod-dflt

  - name: ':book: Linting'
    command: ./ops/bin/lint
    agents:
      queue: cacc-prod-dflt

  - wait

  - name: ':package: Build Javascript'
    command: ./ops/bin/build
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build.tar.gz"

  - wait

  - name: ':rocket: Deploy App'
    command: ./ops/bin/deploy
    branches: master
    agents:
      queue: cacc-prod-dflt
