steps:

  - name: 'Unit Tests'
    command: ./ops/bin/test
    agents:
      queue: hd-dev-dflt

  - block

  - name: ':rocket: Deploy App to Prod'
    command: ./ops/bin/deploy-prod
    branches: 'master'
    agents:
      queue: hd-dev-dflt
