steps:

  - name: ':traffic_light: Unit Tests'
    command: ./ops/bin/test
    agents:
      queue: cacc-prod-dflt

  - name: ':book: Linting'
    command: ./ops/bin/lint
    agents:
      queue: cacc-prod-dflt

  - wait

  - name: ':package: :hatched_chick: Build Development Javascript'
    command: ./ops/bin/build development
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build-development.tar.gz"

  - name: ':package: :hatched_chick: Build Integration Javascript'
    command: ./ops/bin/build integration
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build-integration.tar.gz"

  - wait

  - name: ':rocket: :hatched_chick: Deploy Development App'
    command: ./ops/bin/deploy development
    branches: master
    agents:
      queue: cacc-prod-dflt

  - block

  - name: ':rocket: :eagle: Deploy Integration App'
    command: ./ops/bin/deploy integration
    branches: master
    agents:
      queue: cacc-prod-dflt
