steps:

  - name: ':traffic_light: Unit Tests'
    command: ./ops/bin/test
    agents:
      queue: cacc-prod-dflt

  - name: ':book: Linting'
    command: ./ops/bin/lint
    agents:
      queue: cacc-prod-dflt

  - wait

  - block:
    branches: '!master'

  - name: ':package: :hatched_chick: Build Development Javascript'
    command: ./ops/bin/build development
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build-development.tar.gz"

  - name: ':package: :hatched_chick: Build Integration Javascript'
    command: ./ops/bin/build integration
    branches: master
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build-integration.tar.gz"

  - name: ':package: :hatched_chick: Build PDV Javascript'
    command: ./ops/bin/build pdv
    branches: master
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build-pdv.tar.gz"

  - name: ':package: :hatched_chick: Build Preview Javascript'
    command: ./ops/bin/build preview
    branches: master
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build-preview.tar.gz"

  - name: ':package: :hatched_chick: Build Production Javascript'
    command: ./ops/bin/build production
    branches: master
    env:
      REACT_APP_BUILD_NUMBER: ${BUILDKITE_BUILD_NUMBER}
    agents:
      queue: cacc-prod-dflt
    artifact_paths: "build-production.tar.gz"

  - wait

  - name: ':rocket: :hatched_chick: Deploy Development App'
    command: ./ops/bin/deploy development
    agents:
      queue: cacc-prod-dflt

  - wait

  - name: ':white_check_mark: Record "dev" release'
    command: 'myob-release dev sme-web'
    agents:
      queue: cacc-prod-dflt

  - wait

  - name: ':rocket: :eagle: Deploy Integration App'
    command: ./ops/bin/deploy integration
    branches: master
    agents:
      queue: cacc-prod-dflt

  - wait

  - name: ':white_check_mark: Record "preprod" release'
    command: 'myob-release preprod sme-web'
    agents:
      queue: cacc-prod-dflt

  - block:
    branches: master

  - name: ':rocket: :eagle: Deploy PDV App'
    command: ./ops/bin/deploy pdv
    branches: master
    agents:
      queue: cacc-prod-dflt

  - wait

  - name: ':white_check_mark: Record "qa" release'
    command: 'myob-release qa sme-web'
    agents:
      queue: cacc-prod-dflt

  - block:
    branches: master

  - name: ':rocket: :eagle: Deploy Production App'
    command: ./ops/bin/deploy production
    branches: master
    agents:
      queue: cacc-prod-dflt

  - block:
    branches: master

  - name: ':rocket: :eagle: Deploy Preview App'
    command: ./ops/bin/deploy preview
    branches: master
    agents:
      queue: cacc-prod-dflt

  - wait

  - name: ':white_check_mark: Record "prod" release'
    command: 'myob-release prod sme-web'
    agents:
      queue: cacc-prod-dflt
