const ModalTypes = {
  CANCEL: 'CANCEL',
  DELETE: 'DELETE',
  BANKING_RULE: 'BANKING_RULE',
  BULK_UNALLOCATE: 'BULK_UNALLOCATE',
  UNMATCH_TRANSACTION: 'UNMATCH_TRANSACTION',
  DELETE_ATTACHMENT: 'DELETE_ATTACHMENT',
  TRANSFER_MONEY: 'TRANSFER MONEY',
};

export default ModalTypes;
