#!/bin/bash
set -eu

if [ $# -ne 1 ]; then
  echo "usage: $0 [ s3-<qa|prod>-params ]."
  exit 1
fi

PARAMETERS=$1
STACKNAME="slw-claw-${1}-bucket"
REGION=ap-southeast-2

operation() {
  AWS_DEFAULT_REGION=$REGION AWS_REGION=$REGION aws cloudformation describe-stack-resources --stack-name $STACKNAME > /dev/null 2>&1
  exists=$?

  if [ 0 == $exists ]; then
    echo 'update'
  else
    echo 'create'
  fi
}
op=$(operation)
echo "running $op-stack for ${STACKNAME}"

aws cloudformation ${op}-stack \
  --region ${REGION} \
  --stack-name ${STACKNAME} \
  --template-body file://aws/s3-stack.json \
  --parameters file://aws/s3-$PARAMETERS-params.json
