#!/bin/bash
set -eu

if [ $# -ne 1 ]; then
  echo "usage: $0 [ slw-claw-s3-<dev|prod> ]."
  exit 1
fi

${STACKNAME:=slw-claw-bucket}
REGION=ap-southeast-2
PARAMETERS=$1

operation() {
  AWS_DEFAULT_REGION=$REGION AWS_REGION=$REGION aws cloudformation describe-stack-resources --stack-name $STACKNAME > /dev/null 2>&1
  exists=$?

  if [ 0 == $exists ]; then
    echo 'update'
  else
    echo 'create'
  fi
}
op=$(operation)
echo "running $op-stack for ${STACKNAME}"

aws cloudformation ${op}-stack \
  --region ${REGION} \
  --stack-name ${STACKNAME} \
  --template-body file://slw-claw-s3-template.json \
  --parameters file://$PARAMETERS-params.json

