const ModalTypes = {
  CANCEL: 'CANCEL',
  DELETE: 'DELETE',
  BULK_UNALLOCATE: 'BULK_UNALLOCATE',
  BANKING_RULE: 'BANKING_RULE',
  UNMATCH_TRANSACTION: 'UNMATCH_TRANSACTION',
};

export default ModalTypes;
