export const SET_IS_OPEN = Symbol('set the isOpen state');
export const GET_CODE_TO_AUTHORISE = Symbol('Get code to authorise');
export const UPDATE_AUTHORISATION_INFORMATION = Symbol('Update authorisation information');
export const SET_MODAL_TYPE = Symbol('Set the modal type');
export const UPDATE_AUTHORISATION_CODE = Symbol('Update authorisation code');
export const UPDATE_LOGIN_INFO = Symbol('Update login information');
export const AUTHORISE_WITH_CODE = Symbol('Authorise with code');
export const SET_OPENING_CONTEXT = Symbol('Set opening context');
export const SET_ALERT = Symbol('Set alert');
