const InvoiceDetailModalType = {
  CANCEL: 'CANCEL',
  DELETE: 'DELETE',
  EMAIL_INVOICE: 'EMAIL_INVOICE',
  EMAIL_SETTINGS: 'EMAIL_SETTINGS',
  APPLY_PAYMENT_UNSAVED_CHANGES: 'APPLY_PAYMENT_UNSAVED_CHANGES',
  NONE: '',
};

export default InvoiceDetailModalType;
