const InvoiceDetailModalType = {
  CANCEL: 'CANCEL',
  DELETE: 'DELETE',
  EMAIL_INVOICE: 'EMAIL_INVOICE',
  EMAIL_SETTINGS: 'EMAIL_SETTINGS',
  SAVE_AND_CREATE_NEW: 'SAVE_AND_CREATE_NEW',
  SAVE_AND_DUPLICATE: 'SAVE_AND_DUPLICATE',
  APPLY_PAYMENT_UNSAVED_CHANGES: 'APPLY_PAYMENT_UNSAVED_CHANGES',
  EXPORT_PDF: 'EXPORT_PDF',
  REDIRECT_TO_URL: 'REDIRECT_TO_URL',
  NONE: '',
};

export default InvoiceDetailModalType;
