import InvoiceDetailModalType from '../InvoiceDetailModalType';
import SaveActionType from '../SaveActionType';
import formatIsoDate from '../../../valueFormatters/formatDate/formatIsoDate';

const getDefaultState = () => ({
  isAccountLoading: false,
  businessId: '',
  region: '',
  invoiceId: '',
  quoteId: undefined,
  duplicatedInvoiceId: undefined,
  layout: '',
  openSendEmail: undefined,
  openExportPdf: undefined,
  isLoading: true,
  alert: undefined,
  modalType: InvoiceDetailModalType.NONE,
  modalAlert: undefined,
  isModalSubmitting: false,
  isPageEdited: false,
  isSubmitting: false,
  isContactLoading: false,
  saveActionType: SaveActionType.SAVE,
  invoice: {
    id: '',
    layout: '',
    contactId: '',
    address: '',
    note: '',
    invoiceNumber: '',
    purchaseOrderNumber: '',
    issueDate: formatIsoDate(new Date()),
    isAllowOnlinePayments: false,
    isTaxInclusive: true,
    expirationTerm: '',
    expirationDays: '',
    chargeForLatePayment: 0,
    discountForEarlyPayment: 0,
    numberOfDaysForDiscount: 0,
    amountPaid: '0.00',
    lines: [],
  },
  newLine: {
    units: '',
    itemId: '',
    description: '',
    unitPrice: '',
    taxCodeId: '',
    accountId: '',
    discount: '',
    displayDiscount: '',
    amount: '',
    displayAmount: '',
  },
  totals: {
    subTotal: '0.00',
    totalTax: '0.00',
    totalAmount: '0.00',
  },
  itemTemplate: {
    defaultTemplate: '',
    templateOptions: [],
  },
  serviceTemplate: {
    defaultTemplate: '',
    templateOptions: [],
  },
  comments: [],
  serialNumber: '',
  contactOptions: [],
  accountOptions: [],
  taxCodeOptions: [],
  itemOptions: [],
  expirationTermOptions: [],
  emailInvoice: {
    hasEmailReplyDetails: false,
    isEmailMeACopy: false,
    businessName: '',
    ccToEmail: [''],
    fromEmail: '',
    fromName: '',
    messageBody: '',
    subject: '',
    toEmail: [''],
    toName: '',
    attachments: [],
    templateName: '',
  },
  exportPdf: {
    template: '',
  },
  payDirect: {
    isLoading: true,
    isServiceAvailable: false,
    isRegistered: false,
    baseUrl: '',
  },
  isLineAmountDirty: false,
  areLinesCalculating: false,
});

export default getDefaultState;
