export const activeMapping = {
  'quote/quoteList': 'sales',
  'quote/quoteDetail': 'sales',
  'invoice/invoiceList': 'sales',
  'invoice/invoiceDetail': 'sales',
  'invoicePayment/invoicePaymentDetail': 'sales',
  'customerReturn/customerReturnList': 'sales',
  'customerReturn/customerReturnPayRefund': 'sales',
  'customerReturn/customerReturnApplyToSale': 'sales',
  'applyToSale/applyToSale': 'sales',
  'inventory/itemList': 'sales',
  'customerStatement/customerStatementList': 'sales',

  'bill/billList': 'purchases',
  'bill/billDetail': 'purchases',
  'billPayment/billPaymentDetail': 'purchases',
  'supplierReturn/supplierReturnList': 'purchases',
  'supplierReturn/supplierReturnReceiveRefund': 'purchases',
  'supplierReturn/supplierReturnPurchase': 'purchases',

  'banking/bankTransactionList': 'banking',
  'bankReconciliation/bankReconciliation': 'banking',
  'bankingRule/bankingRuleList': 'banking',
  'bankingRule/bankingRuleSpendMoney': 'banking',
  'bankingRule/bankingRuleReceiveMoney': 'banking',
  'bankingRule/bankingRuleInvoice': 'banking',
  'bankingRule/bankingRuleBill': 'banking',
  'bankFeeds/bankFeeds': 'banking',
  'spendMoney/spendMoneyDetail': 'banking',
  'electronicPayments/electronicPaymentsCreate': 'banking',
  'receiveMoney/receiveMoneyDetail': 'banking',
  'transferMoney/transferMoneyDetail': 'banking',
  'transactionList/transactionList': 'banking',
  'payRefund/payRefund': 'banking',
  'receiveRefund/receiveRefund': 'banking',

  'generalJournal/generalJournalDetail': 'accounting',
  'account/accountList': 'accounting',
  'linkedAccounts/linkedAccounts': 'accounting',
  'tax/taxList': 'accounting',
  'prepareBasOrIas/prepareBasOrIas': 'accounting',

  'employee/employeeList': 'payroll',
  'employee/employeeDetail': 'payroll',
  'payRun/payRunList': 'payroll',
  'payRun/payRunCreate': 'payroll',
  'payItem/payItemList': 'payroll',
  'payItem/superPayItem': 'payroll',
  'payItem/wagePayItem': 'payroll',
  'payItem/deductionPayItemDetail': 'payroll',
  'payItem/expensePayItem': 'payroll',
  'payItem/leavePayItem': 'payroll',
  'payrollSettings/payrollSettings': 'payroll',

  'contact/contactList': 'contact',
  'contact/contactDetail': 'contact',

  'inTray/inTray': 'inTray',

  'business/businessDetail': 'business',
  'incomeAllocation/incomeAllocation': 'business',
  'salesSettings/salesSettingsDetail': 'business',
  'user/userList': 'business',
  'user/userDetail': 'business',
  'dataImportExport/dataImportExport': 'business',
};

export const featuresConfig = {
  quoteList: { routeName: 'quote/quoteList' },
  quoteCreate: { routeName: 'quote/quoteDetail', params: { quoteId: 'new' } },
  invoiceList: { routeName: 'invoice/invoiceList' },
  invoiceCreate: { routeName: 'invoice/invoiceDetail', params: { invoiceId: 'new' } },
  invoicePaymentCreate: { routeName: 'invoicePayment/invoicePaymentDetail', params: { invoicePaymentId: 'new' } },
  customerReturnList: { routeName: 'customerReturn/customerReturnList' },
  customerStatementList: { routeName: 'customerStatement/customerStatementList' },
  itemList: { routeName: 'inventory/itemList' },

  billList: { routeName: 'bill/billList' },
  billCreate: { routeName: 'bill/billDetail', params: { billId: 'new' } },
  billPaymentCreate: { routeName: 'billPayment/billPaymentDetail', params: { billPaymentId: 'new' } },
  supplierReturnList: { routeName: 'supplierReturn/supplierReturnList' },

  bankTransactionList: { routeName: 'banking/bankTransactionList' },
  bankReconciliation: { routeName: 'bankReconciliation/bankReconciliation' },
  bankingRuleList: { routeName: 'bankingRule/bankingRuleList' },
  bankFeeds: { routeName: 'bankFeeds/bankFeeds' },
  electronicPaymentCreate: { routeName: 'electronicPayments/electronicPaymentsCreate' },
  spendMoneyCreate: { routeName: 'spendMoney/spendMoneyDetail', params: { spendMoneyId: 'new' } },
  receiveMoneyCreate: { routeName: 'receiveMoney/receiveMoneyDetail', params: { receiveMoneyId: 'new' } },
  transferMoneyCreate: { routeName: 'transferMoney/transferMoneyDetail', params: { transferMoneyId: 'new' } },
  transactionList: { routeName: 'transactionList/transactionList' },

  generalJournalList: { routeName: 'transactionList/transactionList', params: { sourceJournal: 'General' } },
  generalJournalCreate: { routeName: 'generalJournal/generalJournalDetail', params: { generalJournalId: 'new' } },
  accountList: { routeName: 'account/accountList' },
  linkedAccounts: { routeName: 'linkedAccounts/linkedAccounts' },
  taxList: { routeName: 'tax/taxList' },
  prepareBasOrIas: { routeName: 'prepareBasOrIas/prepareBasOrIas' },

  employeeList: { routeName: 'employee/employeeList' },
  employeeCreate: { routeName: 'employee/employeeDetail', params: { employeeId: 'new' } },
  payRunList: { routeName: 'payRun/payRunList' },
  payRunCreate: { routeName: 'payRun/payRunCreate' },
  payItemList: { routeName: 'payItem/payItemList' },
  timesheets: { routeName: '' },
  superPaymentList: { routeName: '' },
  stpReporting: { routeName: '' },

  contactList: { routeName: 'contact/contactList' },
  contactCreate: { routeName: 'contact/contactDetail', params: { contactId: 'new' } },

  reportsStandard: { routeName: 'reportsStandard', params: { type: 'standardReports' } },
  reportsFavourite: { routeName: 'reportsFavourite', params: { type: 'favouriteReports' } },
  reportsCustom: { routeName: 'reportsCustom', params: { type: 'customReports' } },
  reportsException: { routeName: 'reportsException', params: { type: 'exceptionsReports' } },
  reportsPackBuilder: { routeName: 'reportsPackBuilder', params: { type: 'reportPackBuilder' } },
  reportsPdfStyleTemplates: { routeName: 'reportsPdfStyleTemplates' },

  inTrayList: { routeName: 'inTray/inTray' },

  businessDetails: { routeName: 'business/businessDetail' },
  incomeAllocation: { routeName: 'incomeAllocation/incomeAllocation' },
  salesSettings: { routeName: 'salesSettings/salesSettingsDetail' },
  payrollSettings: { routeName: 'payrollSettings/payrollSettings' },
  userList: { routeName: 'user/userList' },
  dataImportExport: { routeName: 'dataImportExport/dataImportExport' },
  myMyobAccount: { routeName: '' },
  subscriptions: { routeName: '' },
  paymentDetails: { routeName: '' },
};

export const reportsMenuItems = [
  'reportsStandard',
  'reportsFavourite',
  'reportsCustom',
  'reportsException',
  'reportsPackBuilder',
  'reportsPdfStyleTemplates',
];
