const ModalType = {
  DELETE: 'DELETE',
  CANCEL: 'CANCEL',
  UNSAVED: 'UNSAVED',
  SAVE_AND_CREATE_NEW: 'SAVE_AND_CREATE_NEW',
  SAVE_AND_DUPLICATE: 'SAVE_AND_DUPLICATE',
  EXPORT_PDF: 'EXPORT_PDF',
  EMAIL_QUOTE: 'EMAIL_QUOTE',
  EMAIL_SETTINGS: 'EMAIL_SETTINGS',
  NONE: '',
};

export default ModalType;
