const InvoiceHistoryStatus = {
  CREATED: 'CREATED',
  CREATED_FROM_QUOTE: 'CREATED_FROM_QUOTE',
  VIEWED_ONLINE: 'VIEWED_ONLINE',
  DOWNLOADED: 'DOWNLOADED',
  PRINTED: 'PRINTED',
  EXPORTED_TO_PDF: 'EXPORTED_TO_PDF',
  PAID_ONLINE: 'PAID_ONLINE',
  PAID_IN_BULK_ONLINE: 'PAID_IN_BULK_ONLINE',
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  BULK_PAYMENT_DECLINED: 'BULK_PAYMENT_DECLINED',
  PAYMENT_RECEIVED: 'PAYMENT_RECEIVED',
  INVOICE_REVERSED: 'INVOICE_REVERSED',
  EMAILED: 'EMAILED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  CREDIT_APPLIED: 'CREDIT_APPLIED',
};
export default InvoiceHistoryStatus;
