const InvoiceDetailModalType = {
  CANCEL: 'CANCEL',
  DELETE: 'DELETE',
  EMAIL_INVOICE: 'EMAIL_INVOICE',
  EMAIL_SETTINGS: 'EMAIL_SETTINGS',
  SAVE_AMOUNT_DUE_WARNING: 'SAVE_AMOUNT_DUE_WARNING',
  SAVE_AND_CREATE_NEW: 'SAVE_AND_CREATE_NEW',
  SAVE_AND_DUPLICATE: 'SAVE_AND_DUPLICATE',
  APPLY_PAYMENT_UNSAVED_CHANGES: 'APPLY_PAYMENT_UNSAVED_CHANGES',
  EXPORT_PDF: 'EXPORT_PDF',
  REDIRECT_TO_URL: 'REDIRECT_TO_URL',
  CREATE_PRE_CONVERSION_INVOICE: 'CREATE_PRE_CONVERSION_INVOICE',
  QUICK_QUOTE: 'QUICK_QUOTE',
  SEND_EINVOICE: 'SEND_EINVOICE',
  SEND_EINVOICE_ABN_WARNING: 'SEND_EINVOICE_ABN_WARNING',
  NONE: '',
};

export default InvoiceDetailModalType;
